BEGIN TRANSACTION;
INSERT INTO "bible_books" (name) VALUES('Genesis');
INSERT INTO "bible_books" (name) VALUES('Exodus');
INSERT INTO "bible_books" (name) VALUES('Leviticus');
INSERT INTO "bible_books" (name) VALUES('Numbers');
INSERT INTO "bible_books" (name) VALUES('Deuteronomy');
INSERT INTO "bible_books" (name) VALUES('Joshua');
INSERT INTO "bible_books" (name) VALUES('Judges');
INSERT INTO "bible_books" (name) VALUES('Ruth');
INSERT INTO "bible_books" (name) VALUES('First Samuel');
INSERT INTO "bible_books" (name) VALUES('Second Samuel');
INSERT INTO "bible_books" (name) VALUES('First Kings');
INSERT INTO "bible_books" (name) VALUES('Second Kings');
INSERT INTO "bible_books" (name) VALUES('First Chronicles');
INSERT INTO "bible_books" (name) VALUES('Second Chronicles');
INSERT INTO "bible_books" (name) VALUES('Ezra');
INSERT INTO "bible_books" (name) VALUES('Nehemiah');
INSERT INTO "bible_books" (name) VALUES('Esther');
INSERT INTO "bible_books" (name) VALUES('Job');
INSERT INTO "bible_books" (name) VALUES('Psalms');
INSERT INTO "bible_books" (name) VALUES('Proverbs');
INSERT INTO "bible_books" (name) VALUES('Ecclesiastes');
INSERT INTO "bible_books" (name) VALUES('Song of Songs');
INSERT INTO "bible_books" (name) VALUES('Isaiah');
INSERT INTO "bible_books" (name) VALUES('Jeremiah');
INSERT INTO "bible_books" (name) VALUES('Lamentations');
INSERT INTO "bible_books" (name) VALUES('Ezekiel');
INSERT INTO "bible_books" (name) VALUES('Daniel');
INSERT INTO "bible_books" (name) VALUES('Hosea');
INSERT INTO "bible_books" (name) VALUES('Joel');
INSERT INTO "bible_books" (name) VALUES('Amos');
INSERT INTO "bible_books" (name) VALUES('Obadiah');
INSERT INTO "bible_books" (name) VALUES('Jonah');
INSERT INTO "bible_books" (name) VALUES('Micah');
INSERT INTO "bible_books" (name) VALUES('Nahum');
INSERT INTO "bible_books" (name) VALUES('Habakkuk');
INSERT INTO "bible_books" (name) VALUES('Zephaniah');
INSERT INTO "bible_books" (name) VALUES('Haggai');
INSERT INTO "bible_books" (name) VALUES('Zechariah');
INSERT INTO "bible_books" (name) VALUES('Malachi');
INSERT INTO "bible_books" (name) VALUES('Matthew');
INSERT INTO "bible_books" (name) VALUES('Mark');
INSERT INTO "bible_books" (name) VALUES('Luke');
INSERT INTO "bible_books" (name) VALUES('John');
INSERT INTO "bible_books" (name) VALUES('Acts');
INSERT INTO "bible_books" (name) VALUES('Romans');
INSERT INTO "bible_books" (name) VALUES('First Corinthians');
INSERT INTO "bible_books" (name) VALUES('Second Corinthians');
INSERT INTO "bible_books" (name) VALUES('Galatians');
INSERT INTO "bible_books" (name) VALUES('Ephesians');
INSERT INTO "bible_books" (name) VALUES('Philippians');
INSERT INTO "bible_books" (name) VALUES('Colossians');
INSERT INTO "bible_books" (name) VALUES('First Thessalonians');
INSERT INTO "bible_books" (name) VALUES('Second Thessalonians');
INSERT INTO "bible_books" (name) VALUES('First Timothy');
INSERT INTO "bible_books" (name) VALUES('Second Timothy');
INSERT INTO "bible_books" (name) VALUES('Titus');
INSERT INTO "bible_books" (name) VALUES('Philemon');
INSERT INTO "bible_books" (name) VALUES('Hebrews');
INSERT INTO "bible_books" (name) VALUES('James');
INSERT INTO "bible_books" (name) VALUES('First Peter');
INSERT INTO "bible_books" (name) VALUES('Second Peter');
INSERT INTO "bible_books" (name) VALUES('First John');
INSERT INTO "bible_books" (name) VALUES('Second John');
INSERT INTO "bible_books" (name) VALUES('Third John');
INSERT INTO "bible_books" (name) VALUES('Jude');
INSERT INTO "bible_books" (name) VALUES('Revelation');
COMMIT;
